encyclopedia/urls.py
from django.urls import path, include
from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:title>/', views.entry_details, name="wiki_entry"),
    path('search', views.search, name="search"),
    path('new_page', views.new_page, name="new_page"),
    path('random', views.random_page, name="random"),
    path('edit/<str:title>/', views.edit, name="edit")

]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from . import util
from django.contrib import messages
from django.urls import reverse
import random
import markdown2


class searchForm(forms.Form):
    query = forms.CharField(label="Search")


def search(request):
    query = request.GET.get('q', '')
    search_results = []
    entries = util.list_entries()
    
   
    for entry in entries:
        if query.lower() in entry.lower():
            search_results.append(entry)
            
            if query.lower() == entry.lower():
                entry_page = "wiki/" + str(query.lower())
                
                return redirect(entry_page)

    return render(request, "encyclopedia/search.html", {
        "results": search_results,
    })


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry_details(request, title):
    entries = util.list_entries()
    entries = [x.lower() for x in entries]
    if title.lower() in entries:
        content = markdown2.markdown(util.get_entry(title))

        return render(request, 'encyclopedia/entry_detail.html', 
            {'title': title, 'content': content})
    
    else:
        messages.error(request, f"{title}: Entry Does Not Exist. See List of current entries:")

        return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


class NewPageForm(forms.Form):
    title = forms.CharField(label="title")
    content = forms.CharField(widget=forms.Textarea(attrs={'name':'body', 'rows':3,'cols':5}))

def new_page(request):
    filenames = util.list_entries()
    if request.method =="POST":    
        form = NewPageForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]

            filenames = [x.lower() for x in filenames]
            
            if title.lower() not in filenames:
                util.save_entry(title, content)
                entry_page = "wiki/" + str(title)
                
                return redirect(entry_page)
            
            else:
                messages.error(request, 'Entry Exists')

        else:
            return render(request,"encyclopedia/new_page.html", {
                "form": form
            })
    
    return render(request, "encyclopedia/new_page.html", {
        "form": NewPageForm()
    })


def random_page(request):
    entries = util.list_entries()
    randomPage = random.choice(entries)
    print(f"{randomPage}")


    entry_page = "wiki/" + str(randomPage.lower())
    return redirect(entry_page)

def edit(request, title):
    content = util.get_entry(title)

    if request.method == "POST":
        contentEdit = request.POST['content']
        
        util.save_entry(title, contentEdit)
        return HttpResponseRedirect(reverse("encyclopedia:wiki_entry", args=[title]))


    return render(request, "encyclopedia/edit.html", {
        'title': title, 'content': content
    })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <textarea formid="content" form="editform" name="content" rows="5" cols="50" > {{ content }}</textarea>
    <form id="editform" action="{% url 'encyclopedia:edit' title %}" method="post">
    {% csrf_token %}
    <input type="submit" value="submit">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry_detail.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

     <div>{{ content|safe }}</div>
     <br>
     <a href="{% url 'encyclopedia:edit' title %}"> Edit Page</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    {% if messages %}
    {% for message in messages %}
        <p> {{ title }} {{ message }}</p>
    {% endfor %}
{% endif %}
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki_entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
   
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>  
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>                  </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}

    <h1> New Entry</h1>
    <form action="{% url 'encyclopedia:new_page' %}" method="post">
        {% if messages %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
{% endif %}
        {% csrf_token %}
        {{ form }}
    <input type="submit" value="Create Page" >
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search Results</h1>



    <ul>
        {% for result in results %}
            <li><a href="{% url 'encyclopedia:wiki_entry' result %}">{{result}}</a></li>
        {% empty %}
            <p>There are no results</p>
        {% endfor %}
        
    </ul>
   
{% endblock %}